server:
  port: 80

spring:
  application:
    name: spring-cloud-consumer-feign-application
eureka:
  client:
    register-with-eureka: false #不向eureka注册自己
    service-url:
      defaultZone: http://eureka-sever-7001.com:7001/eureka/,http://eureka-sever-7002.com:7002/eureka/,http://eureka-sever-7003.com:7003/eureka/