server:
  port: 7002

eureka:
  instance:
    hostname: eureka-sever-7002.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #表示是否向eureka注册中心注册自己
    fetch-registry: false #false：表示自己为注册中心
    service-url:
      defaultZone: http://eureka-sever-7001.com:7001/eureka/,http://eureka-sever-7003.com:7003/eureka/
  server:
    enable-self-preservation: true